variables:
  - &rust 'rust:1.79-bookworm'
  - &buildx_plugin 'woodpeckerci/plugin-docker-buildx:2.1.0'

labels:
  platform: linux/amd64

clone:
  git:
    image: woodpeckerci/plugin-git:2.5.1
    when:
      - event: pull_request
      - event: [push, tag, manual]
        branch: main

steps:
    # The license check has to before the vendor command as otherweise 'cargo install' will not work
  - name: check-licenses
    image: *rust
    commands: 
      - make check-licenses
    when:
      - event: pull_request
      - event: [push, tag, manual]
        branch: main

  - name: vendor
    image: *rust
    commands:
      - make vendor
    when:
      - event: tag

  - name: build-x86
    image: *rust
    commands:
      - apt update
      - apt install -y musl-tools
      - rustup target add x86_64-unknown-linux-musl
      - make test
      - make build-amd64
    when:
      - event: pull_request
      - event: [push, tag, manual]
        branch: main

  - name: build-arm64
    image: *rust
    commands:
      - dpkg --add-architecture arm64
      - apt update
      - apt install -y --no-install-recommends gcc-aarch64-linux-gnu musl-tools libc6-dev:arm64
      - rustup target add aarch64-unknown-linux-musl
      - make build-arm64
    when:
      - event: pull_request
      - event: [push, tag, manual]
        branch: main

  - name: checksum
    image: *rust
    commands:
      - make checksum
    when:
      - event: tag

  - name: publish-distroless
    image: *buildx_plugin
    settings:
      platforms: linux/amd64,linux/arm64
      repo: windsource/picus,ghcr.io/windsource/picus
      auto_tag: true
      default_suffix: "distroless"
      dockerfile: Dockerfile.distroless.multiarch
      # dry_run: true
      logins:
        - registry: https://index.docker.io/v1/
          username:
            from_secret: docker_username
          password:
            from_secret: docker_password
        - registry: https://ghcr.io
          username:
            from_secret: github_username
          password:
            from_secret: github_password
    when:
      event: [push, tag, manual]
      branch: main

  - name: publish-debian
    image: *buildx_plugin
    settings:
      platforms: linux/amd64,linux/arm64
      repo: windsource/picus,ghcr.io/windsource/picus
      auto_tag: true
      dockerfile: Dockerfile.multiarch
      # dry_run: true
      logins:
        - registry: https://index.docker.io/v1/
          username:
            from_secret: docker_username
          password:
            from_secret: docker_password
        - registry: https://ghcr.io
          username:
            from_secret: github_username
          password:
            from_secret: github_password
    when:
      event: [push, tag, manual]
      branch: main

  - name: publish-release
    image: woodpeckerci/plugin-release:0.1.0
    settings:
      files:
        - 'dist/*'
      api_key:
        from_secret: github_password
      title: ${CI_COMMIT_TAG##v}
    when:
      - event: tag