variables:
  - &rust 'rust:1.79-bookworm'
  - &buildx_plugin 'woodpeckerci/plugin-docker-buildx:2.1.0'

labels:
  platform: linux/arm64

clone:
  git:
    image: woodpeckerci/plugin-git:2.5.1
    when:
      - event: pull_request
      - event: [push, tag, manual]
        branch: main

steps:
  - name: build-arm64
    depends_on: []
    image: *rust
    commands:
      - apt update
      - apt install -y musl-tools
      - rustup target add aarch64-unknown-linux-musl
      - export CARGO_HOME=$(pwd)/.cargo/
      - cargo test --target aarch64-unknown-linux-musl
      - cargo build --release --target aarch64-unknown-linux-musl
      - cp target/aarch64-unknown-linux-musl/release/picus target/picus-linux-arm64
    when:
      - event: pull_request
      - event: [push, tag, manual]
        branch: main

  - name: build-x86
    depends_on: []
    image: *rust
    commands:
      - apt update
      - apt install -y gcc-x86-64-linux-gnu musl-tools
      - rustup target add x86_64-unknown-linux-musl
      - export CARGO_HOME=$(pwd)/.cargo/
      - cargo build --release --target x86_64-unknown-linux-musl
      - cp target/x86_64-unknown-linux-musl/release/picus target/picus-linux-amd64
    when:
      - event: pull_request
      - event: [push, tag, manual]
        branch: main

  - name: check-licenses
    depends_on: []
    image: *rust
    commands: 
      - export CARGO_HOME=$(pwd)/.cargo/
      - cargo install cargo-deny
      - cargo deny check licenses
    when:
      - event: pull_request
      - event: [push, tag, manual]
        branch: main

  - name: publish-distroless
    depends_on: [build-arm64, build-x86, check-licenses]
    image: *buildx_plugin
    settings:
      platforms: linux/amd64,linux/arm64
      repo: windsource/picus,ghcr.io/windsource/picus
      auto_tag: true
      default_suffix: "distroless"
      dockerfile: Dockerfile.distroless.multiarch
      # dry_run: true
      logins:
        - registry: https://index.docker.io/v1/
          username:
            from_secret: docker_username
          password:
            from_secret: docker_password
        - registry: https://ghcr.io
          username:
            from_secret: github_username
          password:
            from_secret: github_password
    when:
      event: [push, tag, manual]
      branch: main

  - name: publish-debian
    depends_on: [build-arm64, build-x86, check-licenses]
    image: *buildx_plugin
    settings:
      platforms: linux/amd64,linux/arm64
      repo: windsource/picus,ghcr.io/windsource/picus
      auto_tag: true
      dockerfile: Dockerfile.multiarch
      # dry_run: true
      logins:
        - registry: https://index.docker.io/v1/
          username:
            from_secret: docker_username
          password:
            from_secret: docker_password
        - registry: https://ghcr.io
          username:
            from_secret: github_username
          password:
            from_secret: github_password
    when:
      event: [push, tag, manual]
      branch: main
