variables:
  - &devcon 'ghcr.io/windsource/picus-devcontainer:1.0.1'
  - &buildx_plugin 'woodpeckerci/plugin-docker-buildx:4.2.0'

labels:
  platform: linux/amd64

clone:
  git:
    image: woodpeckerci/plugin-git:2.5.1
    when:
      - event: pull_request
      - event: [push, tag, manual]
        branch: main

steps:
  - name: build-dev-container
    image: *buildx_plugin
    settings:
      repo: ghcr.io/windsource/picus-devcontainer
      dockerfile: .devcontainer/Dockerfile
      context: .devcontainer
      tags_file: .devcontainer/VERSION
      logins:
        - registry: https://ghcr.io
          username:
            from_secret: github_username
          password:
            from_secret: github_password
    when:
      path:
        - ".devcontainer/*"
        - ".woodpecker.yml"
      event: [push, manual]
      branch: main  

    # The license check has to before the vendor command as otherweise 'cargo install' will not work
  - name: check-licenses
    image: *devcon
    commands: 
      - just check-licenses
    when:
      - event: pull_request
      - event: [push, tag, manual]
        branch: main

  - name: vendor
    image: *devcon
    commands:
      - just vendor
    when:
      - event: tag

  - name: build-x86
    image: *devcon
    commands:
      - just test
      - just build-amd64
    when:
      - event: pull_request
      - event: [push, tag, manual]
        branch: main

  - name: build-arm64
    image: *devcon
    commands:
      - just build-arm64
    when:
      - event: pull_request
      - event: [push, tag, manual]
        branch: main

  - name: checksum
    image: *devcon
    commands:
      - just checksum
    when:
      - event: tag

  - name: publish-distroless
    image: *buildx_plugin
    settings:
      platforms: linux/amd64,linux/arm64
      repo: windsource/picus,ghcr.io/windsource/picus
      auto_tag: true
      default_suffix: "distroless"
      dockerfile: Dockerfile.distroless.multiarch
      # dry_run: true
      logins:
        - registry: https://index.docker.io/v1/
          username:
            from_secret: docker_username
          password:
            from_secret: docker_password
        - registry: https://ghcr.io
          username:
            from_secret: github_username
          password:
            from_secret: github_password
    when:
      event: [push, tag, manual]
      branch: main

  - name: publish-debian
    image: *buildx_plugin
    settings:
      platforms: linux/amd64,linux/arm64
      repo: windsource/picus,ghcr.io/windsource/picus
      auto_tag: true
      dockerfile: Dockerfile.multiarch
      # dry_run: true
      logins:
        - registry: https://index.docker.io/v1/
          username:
            from_secret: docker_username
          password:
            from_secret: docker_password
        - registry: https://ghcr.io
          username:
            from_secret: github_username
          password:
            from_secret: github_password
    when:
      event: [push, tag, manual]
      branch: main

  - name: publish-release
    image: woodpeckerci/plugin-release:0.1.0
    settings:
      files:
        - 'dist/*'
      api_key:
        from_secret: github_password
      title: ${CI_COMMIT_TAG##v}
    when:
      - event: tag