FROM gcr.io/distroless/cc-debian11:nonroot

LABEL org.opencontainers.image.source https://github.com/windsource/picus

ARG TARGETOS TARGETARCH
COPY target/${TARGETOS}/${TARGETARCH}/picus /usr/local/bin/picus

CMD ["/usr/local/bin/picus"]
